Add tutorial for geodetic_to_geocentric transformation
fatiando/boule pull request #84
Opened 2021-08-12 15:52 UTC by LL-Geo

Add tutorials for Converting geodetic latitude and height into geocentric latitude and radius

I feel it's better to tell the coordinate and the ellipsoid height first, then go to the gravity disturbance

**Reminders**:

- [x] Run `make format` and `make check` to make sure the code follows the style guide.
- [ ] Add tests for new features or tests that would have caught the bug that you're fixing.
- [ ] Add new public functions/methods/classes to `doc/api/index.rst` and the base `__init__.py` file for the package.
- [ ] Write detailed docstrings for all functions/classes/methods. It often helps to design better code if you write the docstrings first.
- [ ] If adding new functionality, add an example to the docstring, gallery, and/or tutorials.
- [ ] Add your full name, affiliation, and [ORCID](https://orcid.org) (optional) to the `AUTHORS.md` file (if you haven't already) in case you'd like to be listed as an author on the [Zenodo](https://zenodo.org/communities/fatiando) archive of the next release.

2021-10-01 08:55 UTC, leouieda commented
@LL-Geo thanks for this! I'll try have a look at it as soon as possible.

2021-10-04 15:22 UTC, leouieda requested changes
@LL-Geo great stuff! Left a few suggestions to make sure the website builds correctly. The tutorial itself is really good 💯 

You can commit the suggestions directly through GitHub (there should be a "Commit suggestion" button next to each). Once you're done, please give me a ping and I'm happy to merge this ❤️ 

Please also add yourself to the AUTHORS.md file if you'd like. Either in this PR or in a new PR later would be fine. Whatever works best for you.

2021-10-04 15:22 UTC, leouieda commented on doc/index.rst
> +	tutorials/geodetic_to_geocentric.rst
The tab and the lack of a blank line were causing sphinx to miss this.

2021-10-04 15:22 UTC, leouieda commented on tutorials/geodetic_to_geocentric.py
> +==============
```suggestion
Coordinate conversions
==================

```

2021-10-04 15:22 UTC, leouieda commented on tutorials/geodetic_to_geocentric.py
> +==============
The shorter title fits better on the menu bars. We can always explain it better in the text. There also needs to be blank line after and the `=` need to be the same length as the actual title (I know, that's really annoying)

2021-10-04 15:22 UTC, leouieda commented on tutorials/geodetic_to_geocentric.py
> +.. image:: https://github.com/fatiando/boule/tree/master/doc/_static/coordinate.png
```suggestion
.. figure:: ../_static/coordinate.png
    :alt: Depiction of geocentric and geodetic systems with associated coordinates.
    
    CAPTION SHOULD  BE ADDED HERE
```

2021-10-04 15:22 UTC, leouieda commented on tutorials/geodetic_to_geocentric.py
> +.. image:: https://github.com/fatiando/boule/tree/master/doc/_static/coordinate.png
Using the `figure` directive is better because it allows for a caption. Would you mind adding the caption after merging this suggestion?

2021-10-04 15:23 UTC, leouieda commented
I like the figure! Did you make it youself?

2021-10-05 02:15 UTC, LL-Geo commented
> I like the figure! Did you make it youself?

Haha. Yepp. Find a new hobby for making figures :laughing:

2021-10-05 02:21 UTC, LL-Geo commented
> @LL-Geo great stuff! Left a few suggestions to make sure the website builds correctly. The tutorial itself is really good 💯
> 
> You can commit the suggestions directly through GitHub (there should be a "Commit suggestion" button next to each). Once you're done, please give me a ping and I'm happy to merge this ❤️
> 
> Please also add yourself to the AUTHORS.md file if you'd like. Either in this PR or in a new PR later would be fine. Whatever works best for you.

All done! Haha. Thanks for all the comments and suggestions! :wink:

2021-10-06 17:51 UTC, leouieda approved these changes

2021-10-11 08:02 UTC, merged

2021-10-11 08:02 UTC, leouieda commented
🎉  Congrats on the first PR, @LL-Geo! Hopefully the first of many 🙂